# Generated by Django 5.2.4 on 2025-07-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('about', models.TextField(max_length=300)),
                ('category', models.CharField(max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1)),
                ('email', models.EmailField(max_length=254)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
