# Generated by Django 5.2.4 on 2025-07-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_workers_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workers',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='workers',
            name='category',
            field=models.CharField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('carpenter', 'Carpenter'), ('mechanic', 'Mechanic')], max_length=30),
        ),
        migrations.AlterField(
            model_name='workers',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
