# Generated by Django 5.2.4 on 2025-07-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_certificates_workers_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
