# Generated by Django 5.2.4 on 2025-07-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_workers_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='workers',
            name='service_areas',
            field=models.ManyToManyField(to='services.serviceareas'),
        ),
    ]
