# Generated by Django 5.2.4 on 2025-07-26 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_serviceareas_workers_service_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='service_areas',
        ),
        migrations.AddField(
            model_name='serviceareas',
            name='worker',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='service_area', to='services.workers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workers',
            name='profile_img',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('comment', models.CharField(max_length=200)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='services.workers')),
            ],
        ),
        migrations.CreateModel(
            name='Degrees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='services.workers')),
            ],
        ),
        migrations.DeleteModel(
            name='Certificates',
        ),
    ]
