# Generated by Django 5.2.4 on 2025-07-28 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('times', models.CharField(choices=[('9am', '9:00AM - 10:00 AM'), ('10am', '10:00AM - 11:00 AM'), ('1am', '1:00PM - 2:00 PM'), ('3am', '3:00PM - 4:00 PM')])),
                ('comment', models.TextField(max_length=300)),
                ('worker', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appoiment', to='accounting.profile')),
            ],
        ),
    ]
