# Generated by Django 5.2.4 on 2025-07-29 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_merge_0002_appoiment_0002_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appoiment',
        ),
    ]
