# Generated by Django 5.2.4 on 2025-07-29 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_delete_appoiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appoiment_worker', to='accounting.profile'),
        ),
    ]
